# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'DouYuTV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'NJAFNetworking’
pod 'MJExtension’
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJRefresh'

end
